from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Any

from app.schemas.trading import MarketQuote, OrderRequest


class BrokerAdapter(ABC):
    @abstractmethod
    async def connect(self) -> None: ...
    @abstractmethod
    async def disconnect(self) -> None: ...
    @abstractmethod
    async def get_account(self) -> dict[str, Any]: ...
    @abstractmethod
    async def get_positions(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def get_orders(self) -> list[dict[str, Any]]: ...
    @abstractmethod
    async def get_market_price(self, symbol: str) -> MarketQuote: ...
    @abstractmethod
    async def get_short_availability(self, symbol: str) -> bool: ...
    @abstractmethod
    async def get_buying_power(self) -> Decimal: ...
    @abstractmethod
    async def submit_order(self, request: OrderRequest, quantity: Decimal) -> dict[str, Any]: ...
    @abstractmethod
    async def submit_bracket_order(
        self, request: OrderRequest, quantity: Decimal
    ) -> dict[str, Any]: ...
    @abstractmethod
    async def cancel_order(self, order_id: str) -> dict[str, Any]: ...
    @abstractmethod
    async def close_position(
        self, symbol: str, quantity: Decimal | None = None
    ) -> dict[str, Any]: ...
    @abstractmethod
    async def get_order_status(self, order_id: str) -> dict[str, Any]: ...
    @abstractmethod
    async def get_trade_history(self) -> list[dict[str, Any]]: ...
