'use client';

import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, AreaChart, BarChart3, Bell, Bot, CalendarDays, ChartCandlestick, ChevronDown, Clock3, Command, FileClock, Gauge, LayoutDashboard, ListOrdered, Menu, PlugZap, Power, Radar, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, TrendingUp, UserRound, WalletCards, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Command as CommandMenu, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';

declare global {
  interface Document {
    modelContext?: {
      registerTool(tool: { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean; untrustedContentHint: boolean }; execute(input: unknown): unknown }, options: { signal: AbortSignal }): void | Promise<void>;
    };
  }
}

const nav = [[LayoutDashboard,'Dashboard'],[Radar,'Scanner'],[ChartCandlestick,'Watchlist'],[WalletCards,'Positions'],[ListOrdered,'Orders'],[FileClock,'Trades'],[BarChart3,'Analytics'],[Bot,'Agent'],[Command,'Logs'],[Settings,'Settings']] as const;
const metrics = [['Account equity','501.42 CZK','+0.28%',true],['Buying power','1,002.84 CZK','2.0× margin',false],['Today P&L','+1.42 CZK','+0.28%',true],['Current risk','12.40 CZK','2.47% equity',false]] as const;
const scanner = [['AMD','132.08','-4.82%','2.8×','74','Downtrend','82','2.4'],['TSLA','318.44','+3.17%','1.9×','69','Momentum','76','2.1'],['PLTR','141.21','-2.36%','2.2×','72','Weakness','71','2.8']];
const symbolPrices:Record<string,number>={AMD:132.08,TSLA:318.44,PLTR:141.21,NVDA:116.46,AAPL:226.34};

function SearchPalette({open,onOpenChange,onNavigate,onInvest}:{open:boolean;onOpenChange:(value:boolean)=>void;onNavigate:(value:string)=>void;onInvest:(symbol:string)=>void}){
  return <CommandDialog open={open} onOpenChange={onOpenChange} title="Vyhledávání DeeTrader" description="Vyhledejte sekci nebo instrument"><CommandMenu><CommandInput placeholder="Hledat sekci nebo ticker…"/><CommandList><CommandEmpty>Nic nebylo nalezeno.</CommandEmpty><CommandGroup heading="Sekce">{nav.map(([Icon,label])=><CommandItem key={label} value={label} onSelect={()=>{onNavigate(label);onOpenChange(false)}}><Icon/>{label}</CommandItem>)}</CommandGroup><CommandGroup heading="Instrumenty">{Object.entries(symbolPrices).map(([symbol,price])=><CommandItem key={symbol} value={`${symbol} ${price}`} onSelect={()=>{onInvest(symbol);onOpenChange(false)}}><ChartCandlestick/><b>{symbol}</b><span className="command-price">{price.toFixed(2)} USD</span></CommandItem>)}</CommandGroup></CommandList></CommandMenu></CommandDialog>;
}

function InvestmentDialog({open,onOpenChange,initialSymbol}:{open:boolean;onOpenChange:(value:boolean)=>void;initialSymbol:string}){
  const [symbol,setSymbol]=useState(initialSymbol); const [amount,setAmount]=useState('100'); const [prepared,setPrepared]=useState(false); const [placed,setPlaced]=useState(false);
  const price=symbolPrices[symbol.toUpperCase()]??100; const numericAmount=Math.max(0,Number(amount)||0); const quantity=numericAmount/price;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="trade-dialog"><DialogHeader><div className="trade-dialog-title"><span><TrendingUp size={18}/></span><div><DialogTitle>Nová PAPER investice</DialogTitle><DialogDescription>Připravte testovací pokyn bez použití skutečných peněz.</DialogDescription></div><Badge className="paper-badge">PAPER</Badge></div></DialogHeader>{placed?<div className="order-success"><ShieldCheck size={28}/><strong>PAPER pokyn byl vytvořen</strong><span>{quantity.toFixed(4)} {symbol.toUpperCase()} za přibližně {numericAmount.toFixed(2)} USD</span></div>:<><div className="balance-banner"><span>Dostupný zůstatek</span><strong>451.22 CZK</strong><small>Buying power 1,002.84 CZK</small></div><div className="trade-fields"><label htmlFor="trade-symbol">Ticker</label><Input id="trade-symbol" value={symbol} onChange={e=>{setSymbol(e.target.value.toUpperCase());setPrepared(false)}} maxLength={8}/><label htmlFor="trade-amount">Částka v USD</label><Input id="trade-amount" type="number" min="1" step="1" value={amount} onChange={e=>{setAmount(e.target.value);setPrepared(false)}}/></div>{prepared&&<div className="order-preview"><div><span>Odhadovaná cena</span><b>{price.toFixed(2)} USD</b></div><div><span>Počet kusů</span><b>{quantity.toFixed(4)}</b></div><div><span>Typ pokynu</span><b>Market · BUY</b></div><p>Modelový pokyn pro testování. Před reálným obchodem ověřte cenu, riziko a vhodnost investice.</p></div>}</>}<DialogFooter>{placed?<Button onClick={()=>onOpenChange(false)}>Hotovo</Button>:prepared?<><Button variant="outline" onClick={()=>setPrepared(false)}>Zpět</Button><Button className="agent-button" disabled={!numericAmount||!symbol.trim()} onClick={()=>setPlaced(true)}>Potvrdit PAPER pokyn</Button></>:<Button className="agent-button" disabled={!numericAmount||!symbol.trim()} onClick={()=>setPrepared(true)}>Zkontrolovat pokyn</Button>}</DialogFooter></DialogContent></Dialog>;
}

type BrokerInfo={provider:string;environment:string;orderSubmissionEnabled:boolean;connected:boolean};

function TradingModeDialog({open,onOpenChange,broker}:{open:boolean;onOpenChange:(value:boolean)=>void;broker:BrokerInfo}){
  const liveReady=broker.connected&&broker.provider==='ibkr'&&broker.environment==='live'&&broker.orderSubmissionEnabled;
  const ibkrOrdersReady=broker.provider==='ibkr'&&broker.orderSubmissionEnabled;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="mode-dialog"><DialogHeader><div className="mode-dialog-title"><span><AlertTriangle size={19}/></span><div><DialogTitle>Přepnutí obchodního režimu</DialogTitle><DialogDescription>LIVE režim může odesílat skutečné pokyny a pracovat se skutečnými penězi.</DialogDescription></div></div></DialogHeader><div className="mode-choice"><button className={broker.environment!=='live'?'selected':''} onClick={()=>onOpenChange(false)}><b>PAPER</b><span>Bezpečné testování</span></button><button className={broker.environment==='live'?'selected live':''}><b>LIVE</b><span>Skutečné peníze</span></button></div><div className="live-checks"><div><span className={`status-dot ${broker.connected?'online':''}`}/><span>Backend a broker připojen</span><b>{broker.connected?'OK':'CHYBÍ'}</b></div><div><span className={`status-dot ${broker.provider==='ibkr'?'online':''}`}/><span>Provider Interactive Brokers</span><b>{broker.provider==='ibkr'?'OK':'CHYBÍ'}</b></div><div><span className={`status-dot ${broker.environment==='live'?'online':''}`}/><span>Server spuštěn v LIVE prostředí</span><b>{broker.environment==='live'?'OK':'CHYBÍ'}</b></div><div><span className={`status-dot ${ibkrOrdersReady?'online':''}`}/><span>Odesílání IBKR pokynů povoleno</span><b>{ibkrOrdersReady?'OK':'CHYBÍ'}</b></div></div>{liveReady?<div className="live-ready"><ShieldCheck size={18}/><span>LIVE režim je nakonfigurován a aktivní.</span></div>:<div className="live-blocked"><AlertTriangle size={18}/><div><b>LIVE režim je bezpečně zablokovaný</b><span>V konfiguraci serveru nastavte IBKR, LIVE prostředí a samostatné povolení pokynů. Potom DeeTrader restartujte.</span></div></div>}<DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Zavřít</Button><Button variant="destructive" disabled={!liveReady}>{liveReady?'LIVE je aktivní':'LIVE není připraven'}</Button></DialogFooter></DialogContent></Dialog>;
}

function BrokerConnectionDialog({open,onOpenChange,onConnected}:{open:boolean;onOpenChange:(value:boolean)=>void;onConnected:()=>void}){
  const [method,setMethod]=useState<'gateway'|'oauth'>('gateway'); const [baseUrl,setBaseUrl]=useState('https://127.0.0.1:5000/v1/api'); const [accountId,setAccountId]=useState(''); const [accessToken,setAccessToken]=useState(''); const [adminPassword,setAdminPassword]=useState(''); const [verifyTls,setVerifyTls]=useState(false); const [status,setStatus]=useState<'idle'|'connecting'|'success'|'error'>('idle'); const [message,setMessage]=useState('');
  const connect=async()=>{setStatus('connecting');setMessage('Ověřuji přihlášení a IBKR session…');const api=process.env.NEXT_PUBLIC_API_URL??'http://127.0.0.1:8000';try{const login=await fetch(`${api}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@deetrader.local',password:adminPassword})});if(!login.ok)throw new Error('Neplatné administrátorské heslo DeeTrader.');const auth=await login.json() as {access_token?:string};if(!auth.access_token)throw new Error('Přihlášení nevrátilo přístupový token.');const response=await fetch(`${api}/api/v1/broker/connect`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth.access_token}`},body:JSON.stringify({method,base_url:baseUrl,account_id:accountId||null,access_token:method==='oauth'?accessToken:null,verify_tls:verifyTls,environment:'paper',order_submission_enabled:false})});const result=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(typeof result.detail==='string'?result.detail:'IBKR připojení se nezdařilo.');setAccessToken('');setAdminPassword('');setStatus('success');setMessage('IBKR je připojeno v PAPER režimu pouze pro aktuální běh serveru.');onConnected()}catch(error){setAccessToken('');setStatus('error');setMessage(error instanceof Error?error.message:'IBKR připojení se nezdařilo.')}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="broker-dialog"><DialogHeader><div className="trade-dialog-title"><span><PlugZap size={18}/></span><div><DialogTitle>Připojit Interactive Brokers</DialogTitle><DialogDescription>Nejprve připojte PAPER účet. LIVE pokyny zůstávají samostatně zablokované.</DialogDescription></div></div></DialogHeader><div className="connection-methods"><button className={method==='gateway'?'selected':''} onClick={()=>{setMethod('gateway');setBaseUrl('https://127.0.0.1:5000/v1/api');setVerifyTls(false);setStatus('idle')}}><b>Client Portal Gateway</b><span>Doporučeno pro osobní účet</span></button><button className={method==='oauth'?'selected':''} onClick={()=>{setMethod('oauth');setBaseUrl('https://api.ibkr.com/v1/api');setVerifyTls(true);setStatus('idle')}}><b>OAuth session</b><span>Pro registrované API aplikace</span></button></div><div className="connection-note"><ShieldCheck size={17}/><span>{method==='gateway'?'Gateway musí běžet na tomto počítači a musíte v něm být přihlášeni přes prohlížeč. IBKR nepodporuje automatizaci tohoto přihlášení.':'Vložte krátkodobý bearer/SSO token vytvořený vaším registrovaným OAuth řešením. Nejde o běžný trvalý API klíč.'}</span></div><div className="broker-fields"><label htmlFor="ibkr-url">IBKR API URL</label><Input id="ibkr-url" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)}/><label htmlFor="ibkr-account">Account ID <small>volitelné</small></label><Input id="ibkr-account" value={accountId} onChange={e=>setAccountId(e.target.value)} placeholder="např. U1234567"/>{method==='oauth'&&<><label htmlFor="ibkr-token">OAuth bearer / SSO token</label><Input id="ibkr-token" type="password" autoComplete="off" value={accessToken} onChange={e=>setAccessToken(e.target.value)} placeholder="Token se neukládá v prohlížeči"/></>}<label htmlFor="admin-password">Heslo správce DeeTrader</label><Input id="admin-password" type="password" autoComplete="current-password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} placeholder="Potvrzení lokální změny"/><label className="tls-option"><input type="checkbox" checked={verifyTls} onChange={e=>setVerifyTls(e.target.checked)}/><span>Ověřovat TLS certifikát</span></label></div>{status!=='idle'&&<div className={`connection-status ${status}`}><span className={`status-dot ${status==='success'?'online':''}`}/><span>{message}</span></div>}<DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Zavřít</Button><Button className="agent-button" onClick={()=>void connect()} disabled={status==='connecting'||!baseUrl||!adminPassword||(method==='oauth'&&!accessToken)}>{status==='connecting'?'Připojuji…':'Otestovat a připojit'}</Button></DialogFooter></DialogContent></Dialog>;
}

function MiniChart(){return <svg viewBox="0 0 900 250" className="mini-chart" preserveAspectRatio="none" aria-label="Equity curve for the last month"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2dd4bf" stopOpacity=".25"/><stop offset="1" stopColor="#2dd4bf" stopOpacity="0"/></linearGradient></defs>{[35,85,135,185,235].map(y=><line key={y} x1="0" y1={y} x2="900" y2={y} stroke="#26303b"/>)}<path d="M0 210 C45 204 62 191 105 196S170 175 210 181S275 142 325 151S382 124 430 139S485 96 535 105S610 88 660 99S724 60 772 72S842 39 900 49L900 250L0 250Z" fill="url(#fill)"/><path d="M0 210 C45 204 62 191 105 196S170 175 210 181S275 142 325 151S382 124 430 139S485 96 535 105S610 88 660 99S724 60 772 72S842 39 900 49" fill="none" stroke="#2dd4bf" strokeWidth="2.5"/><circle cx="900" cy="49" r="4" fill="#2dd4bf"/></svg>}

function SecondaryView({active,agent,onConnectBroker,broker}:{active:string;agent:string;onConnectBroker:()=>void;broker:BrokerInfo}){
  if(active==='Scanner')return <Card className="table-card secondary-card"><div className="card-title"><div><span>Market scanner</span><small>Price 50–350 · Relative volume ≥ 1.5× · Shortable</small></div><Button size="sm">Run scan</Button></div><Table><TableHeader><TableRow>{['Ticker','Price','Change','Rel. volume','RSI','Trend','Confidence','R:R','Action'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{scanner.map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={i}>{i===0?<b>{v}</b>:v}</TableCell>)}<TableCell><Button variant="outline" size="sm">Analyze</Button></TableCell></TableRow>)}</TableBody></Table></Card>;
  if(active==='Analytics')return <><div className="metric-grid">{[['Total trades','24','This month'],['Win rate','58.3%','14 wins'],['Profit factor','1.74','Gross P&L'],['Max drawdown','7.2%','36.12 CZK']].map(([x,y,z])=><Card className="metric-card" key={x}><div><span>{x}</span><BarChart3 size={16}/></div><strong>{y}</strong><small>{z}</small></Card>)}</div><Card className="chart-card secondary-chart"><div className="card-title"><div><span>Performance and drawdown</span><strong>+8.64%</strong></div><Badge variant="outline">PAPER</Badge></div><div className="chart-wrap"><MiniChart/></div></Card></>;
  if(active==='Agent'||active==='Logs')return <div className="agent-grid"><Card className="activity-card"><div className="card-title"><div><span>Trading agent</span><small>Deterministic controls</small></div><Badge variant="outline">{agent}</Badge></div>{[['Current operation','Waiting'],['Last scan','14:32:18'],['Symbols scanned','34'],['Signals found','3'],['Trades rejected','2'],['Open trades','1']].map(([x,y])=><div className="settings-row" key={x}><span>{x}</span><b>{y}</b></div>)}<Button variant="destructive" className="kill-button">Emergency stop</Button></Card><Card className="activity-card"><div className="card-title"><span>Live system log</span><Badge variant="outline">STREAMING</Badge></div>{['SCANNER NVDA candidate detected','STRATEGY breakdown-short confidence=78','AI unavailable — continuing without AI','RISK position risk=12.40 CZK','ORDER waiting for approval'].map((x,i)=><div className="log-row" key={x}><span className={i===2?'warn-dot':'status-dot online'}/><div><b>{x}</b><small>14:32:{String(11+i).padStart(2,'0')}</small></div></div>)}</Card></div>;
  if(active==='Settings')return <div className="settings-grid"><Card className="activity-card"><div className="card-title"><div><span>Risk controls</span><small>Critical changes require confirmation</small></div><ShieldCheck size={17}/></div>{[['Risk per trade','5%'],['Daily loss limit','10%'],['Weekly loss limit','100 CZK'],['Maximum positions','1'],['Minimum R:R','2.0'],['Trades per day','5']].map(([x,y])=><label className="settings-row" key={x}><span>{x}</span><input defaultValue={y}/></label>)}<Button size="sm">Review changes</Button></Card><Card className="activity-card broker-settings"><div className="card-title"><div><span>Broker & execution</span><small>Připojení je aktivní pouze pro aktuální běh serveru</small></div><Badge className={broker.environment==='live'?'live-badge':'paper-badge'}>{broker.environment.toUpperCase()}</Badge></div>{[['Broker',broker.provider==='ibkr'?'Interactive Brokers':'Paper broker'],['Connection',broker.connected?'Connected':'Offline'],['Account ID','••••••••••'],['Execution mode','Manual'],['Live trading',broker.environment==='live'?'Enabled':'Disabled'],['Order submission',broker.orderSubmissionEnabled&&broker.provider==='ibkr'?'Enabled':'Disabled']].map(([x,y])=><div className="settings-row" key={x}><span>{x}</span><b>{y}</b></div>)}<Button className="connect-broker-button" onClick={onConnectBroker}><PlugZap size={15}/>{broker.provider==='ibkr'?'Změnit IBKR připojení':'Připojit Interactive Brokers'}</Button><p className="credentials-note"><ShieldCheck size={14}/>Tokeny se v prohlížeči ani odpovědích API neukládají ani nezobrazují.</p></Card></div>;
  const labels=active==='Positions'?['Ticker','Direction','Quantity','Entry','Current price','Stop loss','Take profit','Unrealized P&L','Action']:active==='Orders'?['Order ID','Ticker','Side','Type','Quantity','Status','Submitted','Action']:active==='Trades'?['Trade ID','Date','Ticker','Direction','Entry','Exit','P&L','Strategy','Exit reason']:['Ticker','Price','Change','Volume','Trend','Strategy','Alert','Action'];
  return <Card className="table-card secondary-card"><div className="card-title"><div><span>{active}</span><small>Paper environment · real-time view</small></div><Button variant="outline" size="sm">Filters</Button></div><Table><TableHeader><TableRow>{labels.map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow>{labels.map((x,i)=><TableCell key={x}>{i===0?<b>{active==='Orders'?'DT-8F21':active==='Trades'?'TR-1042':'NVDA'}</b>:i===labels.length-1?<Button variant="outline" size="sm">View</Button>:['SHORT','0.42','119.84','116.46','123.10','113.32','+1.42 CZK'][i-1]??'—'}</TableCell>)}</TableRow></TableBody></Table></Card>;
}

export function TradingTerminal(){
  const [active,setActive]=useState('Dashboard'); const [mobile,setMobile]=useState(false); const [agent,setAgent]=useState<'STOPPED'|'RUNNING'>('STOPPED'); const [backendOnline,setBackendOnline]=useState(false); const [now,setNow]=useState<Date|null>(null); const [modeOpen,setModeOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [investOpen,setInvestOpen]=useState(false); const [brokerOpen,setBrokerOpen]=useState(false); const [selectedSymbol,setSelectedSymbol]=useState('AAPL'); const [brokerInfo,setBrokerInfo]=useState<BrokerInfo>({provider:'paper',environment:'paper',orderSubmissionEnabled:false,connected:false});
  useEffect(()=>{let cancelled=false;const api=process.env.NEXT_PUBLIC_API_URL??'http://127.0.0.1:8000';const check=async()=>{try{const health=await fetch(`${api}/health`);if(cancelled)return;setBackendOnline(health.ok);if(health.ok){const response=await fetch(`${api}/api/v1/broker`);if(response.ok){const info=await response.json() as Record<string,unknown>;const provider=typeof info.provider==='string'?info.provider:'paper';const environment=typeof info.environment==='string'?info.environment:'paper';if(!cancelled)setBrokerInfo({provider,environment,orderSubmissionEnabled:Boolean(info.order_submission_enabled),connected:info.connection_state==='CONNECTED'})}}}catch{if(!cancelled){setBackendOnline(false);setBrokerInfo(value=>({...value,connected:false}))}}};void check();const timer=setInterval(()=>{void check()},15000);return()=>{cancelled=true;clearInterval(timer)}},[]);
  useEffect(()=>{const update=()=>setNow(new Date());update();const timer=setInterval(update,1000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const registration=context.registerTool({name:'set_paper_agent_state',title:'Set paper agent state',description:'Start or stop the visible DeeTrader paper agent. This does not enable live trading.',inputSchema:{type:'object',properties:{state:{type:'string',enum:['RUNNING','STOPPED']}},required:['state'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(typeof input!=='object'||input===null||!('state' in input)||((input as {state:unknown}).state!=='RUNNING'&&(input as {state:unknown}).state!=='STOPPED'))throw new Error('state must be RUNNING or STOPPED');const state=(input as {state:'RUNNING'|'STOPPED'}).state;setAgent(state);return {state,tradingMode:'PAPER',liveTrading:false}}},{signal:lifecycle.signal});void Promise.resolve(registration).catch(()=>undefined);return()=>lifecycle.abort()},[]);
  const tradingMode=brokerInfo.environment==='live'?'LIVE':'PAPER';
  const openInvestment=(symbol='AAPL')=>{setSelectedSymbol(symbol);setInvestOpen(true)};
  const refreshBroker=()=>{const api=process.env.NEXT_PUBLIC_API_URL??'http://127.0.0.1:8000';void fetch(`${api}/api/v1/broker`).then(response=>response.json()).then(value=>{const info=value as Record<string,unknown>;const provider=typeof info.provider==='string'?info.provider:'paper';const environment=typeof info.environment==='string'?info.environment:'paper';setBackendOnline(true);setBrokerInfo({provider,environment,orderSubmissionEnabled:Boolean(info.order_submission_enabled),connected:info.connection_state==='CONNECTED'})}).catch(()=>setBackendOnline(false))};
  return <div className="terminal-shell">
    <aside className={`sidebar ${mobile?'sidebar-open':''}`}><div className="brand"><span className="brand-mark"><AreaChart size={19}/></span><span>DeeTrader</span><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X size={18}/></button></div><nav>{nav.map(([Icon,label])=><button key={label} onClick={()=>{setActive(label);setMobile(false)}} className={active===label?'nav-active':''}><Icon size={17}/><span>{label}</span>{label==='Scanner'&&<span className="nav-count">3</span>}</button>)}</nav><div className="sidebar-foot"><div><span className={`status-dot ${backendOnline?'online':''}`}/><span>{brokerInfo.provider==='ibkr'?'IBKR broker':'Paper broker'}</span><b>{backendOnline?'Connected':'Offline'}</b></div><button className={`mode-switch ${tradingMode==='LIVE'?'live':''}`} onClick={()=>setModeOpen(true)} aria-label="Přepnout obchodní režim"><ShieldCheck size={16}/><span>Trading mode</span><Badge className={tradingMode==='LIVE'?'live-badge':'paper-badge'}>{tradingMode}</Badge><ChevronDown size={13}/></button><DropdownMenu><DropdownMenuTrigger className="user-row" aria-label="Otevřít nabídku účtu"><span className="avatar">DT</span><span><strong>Trader</strong><small>Administrator</small></span><ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="account-menu" side="top" align="start" sideOffset={8}><DropdownMenuGroup><DropdownMenuLabel><strong>Trader</strong><span>Administrator · {tradingMode} účet</span></DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onClick={()=>{setActive('Settings');setMobile(false)}}><UserRound/>Nastavení účtu</DropdownMenuItem><DropdownMenuItem onClick={()=>{setActive('Settings');setMobile(false)}}><PlugZap/>Broker a API</DropdownMenuItem></DropdownMenuGroup></DropdownMenuContent></DropdownMenu></div></aside>
    <main className="main-panel"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu size={20}/></button><div className="market-state"><span className="status-dot online"/><span>Market open</span><small>Closes in 4h 26m</small></div><div className="current-datetime" aria-live="off"><span><CalendarDays size={13}/>{now?new Intl.DateTimeFormat('cs-CZ',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Europe/Prague'}).format(now):'--.--.----'}</span><b><Clock3 size={13}/>{now?new Intl.DateTimeFormat('cs-CZ',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'Europe/Prague'}).format(now):'--:--:--'}</b></div><div className="top-statuses"><span><WalletCards size={14}/>Zůstatek <b>501.42 CZK</b></span><span><Activity size={14}/>Broker <b className={backendOnline?'positive':'negative'}>{backendOnline?'Online':'Offline'}</b></span><span><Bot size={14}/>Agent <b>{agent}</b></span><span>Daily P&L <b className="positive">+1.42 CZK</b></span><span>Risk <b>2.47%</b></span></div><div className="top-actions"><Button variant="outline" size="icon" aria-label="Search" onClick={()=>setSearchOpen(true)}><Search size={16}/></Button><Button variant="outline" size="icon" aria-label="Notifications"><Bell size={16}/><i/></Button><button className={tradingMode==='LIVE'?'live-badge top-mode':'paper-badge top-mode'} onClick={()=>setModeOpen(true)}>{tradingMode}</button></div></header>
      <section className="content"><div className="page-heading"><div><p>Trading overview</p><h1>{active}</h1></div><div className="heading-actions"><Button className="invest-button" onClick={()=>openInvestment()}><Sparkles size={15}/>Nová investice</Button><Button variant="outline" onClick={()=>setActive('Settings')}><SlidersHorizontal size={15}/>Configure</Button><Button className="agent-button" onClick={()=>setAgent(agent==='RUNNING'?'STOPPED':'RUNNING')}><Power size={15}/>{agent==='RUNNING'?'Stop agent':'Start agent'}</Button></div></div>
      <div className={`safety-strip ${tradingMode==='LIVE'?'live-strip':''}`}><ShieldCheck size={16}/><span><b>{tradingMode==='LIVE'?'LIVE režim aktivní':'Safe defaults active'}</b> — {tradingMode==='LIVE'?'IBKR live prostředí, skutečné pokyny povoleny':'Manual execution, paper broker, live trading disabled'}</span><Badge variant="outline">0 violations</Badge></div>
      {active==='Dashboard'?<>
      <div className="metric-grid">{metrics.map(([l,v,n,g])=><Card className="metric-card" key={l}><div><span>{l}</span><Gauge size={16}/></div><strong>{v}</strong><small className={g?'positive':''}>{n}</small></Card>)}</div>
      <div className="chart-grid"><Card className="chart-card"><div className="card-title"><div><span>Equity curve</span><strong>501.42 CZK</strong></div><div className="range-tabs">{['1D','1W','1M','3M','YTD','ALL'].map(x=><button key={x} className={x==='1M'?'selected':''}>{x}</button>)}</div></div><div className="chart-wrap"><MiniChart/></div><div className="chart-axis"><span>Aug 08</span><span>Aug 15</span><span>Aug 22</span><span>Aug 29</span><span>Sep 07</span></div></Card><Card className="risk-card"><div className="card-title"><span>Risk utilization</span><Badge variant="outline">LOW</Badge></div><div className="risk-ring"><div><strong>2.47%</strong><span>of equity</span></div></div><dl>{[['Open risk','12.40 CZK'],['Daily loss remaining','48.58 CZK'],['Positions','1 / 1'],['Exposure','9.8%']].map(([x,y])=><div key={x}><dt>{x}</dt><dd>{y}</dd></div>)}</dl></Card></div>
      <Card className="table-card"><div className="card-title"><div><span>Open positions</span><small>Real-time paper portfolio</small></div><Button variant="ghost" size="sm">View all</Button></div><Table><TableHeader><TableRow>{['Ticker','Direction','Qty','Entry / Mark','Stop / Target','P&L','R:R','Strategy','Action'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow><TableCell><b>NVDA</b><small>NASDAQ</small></TableCell><TableCell><Badge className="short-badge">SHORT</Badge></TableCell><TableCell>0.42</TableCell><TableCell>119.84<small>116.46</small></TableCell><TableCell>123.10<small>113.32</small></TableCell><TableCell className="positive"><b>+1.42 CZK</b><small>+2.82%</small></TableCell><TableCell>1 : 2.0</TableCell><TableCell>Breakdown</TableCell><TableCell><Button variant="outline" size="sm">Manage</Button></TableCell></TableRow></TableBody></Table></Card>
      <div className="bottom-grid"><Card className="table-card"><div className="card-title"><div><span>Scanner candidates</span><small>Latest strategy matches</small></div><Badge variant="outline">3 signals</Badge></div><Table><TableHeader><TableRow>{['Ticker','Price','Change','Rel. vol','RSI','Signal','Score','R:R'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{scanner.map(r=><TableRow key={r[0]}>{r.map((v,i)=><TableCell key={i} className={i===2?'negative':i===6?'positive':''}>{i===0?<b>{v}</b>:v}</TableCell>)}</TableRow>)}</TableBody></Table></Card><Card className="activity-card"><div className="card-title"><span>Agent activity</span><Badge variant="outline">{agent}</Badge></div>{['Scanner completed · 34 symbols','Risk rejected PLTR · max positions','NVDA mark updated · 116.46','Paper order filled · NVDA'].map((x,i)=><div className="log-row" key={x}><span className={i===1?'warn-dot':'status-dot online'}/><div><b>{x}</b><small>{['14:32:18','14:31:44','14:30:09','13:52:31'][i]}</small></div></div>)}</Card></div>
      </>:<SecondaryView active={active} agent={agent} broker={brokerInfo} onConnectBroker={()=>setBrokerOpen(true)}/>} 
      </section></main><SearchPalette open={searchOpen} onOpenChange={setSearchOpen} onNavigate={setActive} onInvest={openInvestment}/><InvestmentDialog key={`${selectedSymbol}-${investOpen}`} open={investOpen} onOpenChange={setInvestOpen} initialSymbol={selectedSymbol}/><TradingModeDialog open={modeOpen} onOpenChange={setModeOpen} broker={brokerInfo}/><BrokerConnectionDialog open={brokerOpen} onOpenChange={setBrokerOpen} onConnected={refreshBroker}/>
  </div>;
}
